server:
    port: 2022
    tomcat:
        uri-encoding: UTF-8
    servlet:
        context-path: /covid19-report

spring:
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    datasource:
        platform: MYSQL
        continue-on-error: false
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/covid19_report?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: mushroom
mybatis:
    mapper-locations: classpath:mapper/**/*.xml

logging:
    level:
        root: info
